%% File with constnt settings for CCLM calibration suite
%
%% directories:
%  -- simdir
%  -- obsdir
%%  calibration time period
%  --nmonths
%  --nyear
%  --nyearstart
%  --nyearend
%% Parameters, simulations and domains
%  --nparam
%  --nsim
%  --expid
%  --paramn
%  --paramnt
%  --regnames
%  --default param
%  --range of param
%% Independent simulations
%  --nind
%  --valdata


simdir='/hymet/ssilje/cosmopompa_calibration/modeloutput/output_2005-2009/';
obsdir='/hymet/ssilje/cosmopompa_calibration/observations_2005-2009/';

nmonths=60;
nyear=5;

% For the internal variability stddata_2000-2009.mat
nyearstart=6;
nyearend=10;
nparam=8; %number of parameters
nsim=128; %number of simulations
expid={'rl','v','tk','u','ra','f','l','tu'};
% Define Parameters
paramn={'rlam_heat','v0snow','tkhmin','uc1','radfac','roodtp','l_g','tur_len'}; % No TEX interpreter
paramnt={'rlam\_heat','v0snow','tkhmin','uc1','radfac','roodtp','l\_g','tur\_len'}; % No TEX interpreter
regnames={'BI','IP','FR','ME','SC','AL','MD','EA'};


%%% To reduce the chances of typing in wrong numbers, copy in from
%%% INPUT_ORG in the input folder.
tkhmin=1;
v0snow=20.0;
rlam_heat=1.0;
qi0=0.0;
uc1=0.8;
l_g=1.59;
tur_len=500.0;
fac_rootdp2=1.0;
radfac=0.6;

% Default parameters
default={[rlam_heat v0snow tkhmin uc1 radfac fac_rootdp2 log(l_g) tur_len]};

%%% To reduce the chances of typing in wrong numbers, copy in the line from
%%% the script generate_input.m here:

rlam_heatn=0.1;
rlam_heatx=2.0;
v0snown=10.0;
v0snowx=30.0;
tkhminn=0.1;
tkhminx=2.0;
uc1n=0.0;
uc1x=1.6;
radfacn=0.3;
radfacx=0.9;
fac_rootdp2n=0.5;
fac_rootdp2x=1.5;
l_gn=0.25;
l_gx=10;
tur_lenn=60.0;
tur_lenx=1000.0;

% Parameter ranges (min,max)


range={[rlam_heatn rlam_heatx]; % rlam_heat
    [v0snown v0snowx]; % v0snow
    [tkhminn tkhminx];% tkhmin
    [uc1n uc1x]; % uc1
    [radfacn radfacx];% radfac
    [fac_rootdp2n fac_rootdp2x];% roodtp
    [log(l_gn) log(l_gx)]; %l_g --> exponential.
    [tur_lenn tur_lenx]};% tur_len



nind=12; % number of independent simulations
%%% Matrix for 11 independent simulations
% The independent runs can be generated by this function:
%[xexp]=create_validation_experiments(parameters,lhacc)

valdata=[1.81 20 1.43 0.48 0.6 1.4 log(5.1250) 154; %IND1
    1.43 20 1.05 1.12 0.48 0.6 log(3.175) 906; %IND2
    0.29 16 1.81 0.8  0.36 1.2 log(1.225) 342; %IND3
    0.67 28 0.67 0.16 0.84 1 log(9.025) 718; %IND4
    1.05 12 0.28 1.44  0.72 0.8 log(7.075) 530; %IND5
    0.2066 15.5 0.8388 0.5911 0.5719 0.6342 log(0.53) 548.239; % IND6 --> %reference_opt
    0.2790 17.6 0.9879 0.1503 0.5968 0.8548 log(0.3834) 568.4869; % IND7 --> reference_opt2
    0.8023 24.5 1.3378 0.8595 0.4862 1.0420 log(3.4750) 505.9076; % IND8 --> reference_op3
    0.1351 17.2438 0.8182 0.5284 0.5834 0.6599 0.1806 380.0069; % IND9 -->  reference_opt4
    0.5999 23.0132 1.1693 0.5386 0.5934 0.8487 1.2728 562.9077; % IND10 --> reference_opt6
    0.7173 25.5949 1.3692 0.7494 0.5934 0.9605 1.2728 562.9077; % IND11 --> reference_opt5
    0.7254 24.3945 1.4567 0.9039 0.6 1.0419 1.59 500]; % IND12 --> reference_opt7


